services:
#   scrapers:
#     build:
#       context: ./scrapers
#       dockerfile: Dockerfile
#     depends_on:
#       - sqs
  
  # processor:
  #   build:
  #     context: ./processor
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - sqs

  api:
    build:
      context: ./crud-api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/music_charts"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - mynetwork
  
  sqs:
    image: softwaremill/elasticmq:latest
    container_name: sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_charts
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: