services:
  # scrapers:
  #   build:
  #     context: ./scrapers
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - sqs
  
  # processor:
  #   build:
  #     context: ./processor
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - sqs

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
  
  # sqs:
  #   image: softwaremill/elasticmq:latest
  #   container_name: sqs
  #   ports:
  #     - "9324:9324"
  #   volumes:
  #     - ./elasticmq.conf:/opt/elasticmq.conf

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: