services:
  youtube-daily-scheduler:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
      args:
        SCHEDULER_MODULE: "scrapers.youtubeScraper.youtubeChartsDaily"
    # environment:
    #   - YOUTUBE_CHARTS_URL_KEY=${YOUTUBE_CHARTS_URL_KEY}
    #   - YOUTUBE_CHARTS_COOKIE=${YOUTUBE_CHARTS_COOKIE}
    #   - YOUTUBE_CHARTS_API_KEY=${YOUTUBE_CHARTS_API_KEY}
    #   - YOUTUBE_TRENDS_COOKIE=${YOUTUBE_TRENDS_COOKIE}
    #   - YOUTUBE_TRENDS_API_KEY=${YOUTUBE_TRENDS_API_KEY}
    # env_file:
    #   - ./scrapers/.env
    depends_on:
      - sqs
    networks:
      - mynetwork


  youtube-weekly-scheduler:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
      args:
        SCHEDULER_MODULE: "scrapers.youtubeScraper.youtubeChartsWeekly"
    # environment:
    #   - YOUTUBE_CHARTS_URL_KEY=${YOUTUBE_CHARTS_URL_KEY}
    #   - YOUTUBE_CHARTS_COOKIE=${YOUTUBE_CHARTS_COOKIE}
    #   - YOUTUBE_CHARTS_API_KEY=${YOUTUBE_CHARTS_API_KEY}
    # env_file:
    #   - ./scrapers/.env
    depends_on:
      - sqs
    networks:
      - mynetwork

  tiktok-scheduler:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
      args:
        SCHEDULER_MODULE: "scrapers.tiktokBillboardScraper.tiktokScraper"
    depends_on:
      - sqs
    networks:
      - mynetwork

  spotify-daily-scheduler:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
      args:
        SCHEDULER_MODULE: "scrapers.spofityScraper.spotifyChartsDaily"
    # environment:
    #   SPOTIFY_API_KEY_DAILY: ${SPOTIFY_API_KEY_DAILY}
    # env_file:
    #   - ./scrapers/.env
    depends_on:
      - sqs
    networks:
      - mynetwork

  spotify-weekly-scheduler:
    build:
      context: ./scrapers
      dockerfile: Dockerfile
      args:
        SCHEDULER_MODULE: "scrapers.spofityScraper.spotifyChartsWeekly"
    # environment:
    #   SPOTIFY_API_KEY_DAILY: ${SPOTIFY_API_KEY_WEEKLY}
    # env_file:
    #   - ./scrapers/.env
    depends_on:
      - sqs
    networks:
      - mynetwork

  api:
    build:
      context: ./crud-api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/music_charts"
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - mynetwork

  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    networks:
      - mynetwork
    depends_on:
      - sqs  

  sqs:
    image: softwaremill/elasticmq:latest
    container_name: sqs
    ports:
      - "9324:9324"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: music_charts
      
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data: