service: skibidi-pipeline

provider:
  name: aws
  runtime: python3.9  
  region: us-east-1 
  environment:
    file: .env

functions:
  process:
    handler: crud-api/app.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /genres
          method: any
      - http:
          path: /genres/{proxy+}
          method: any
      - http:
          path: /songs
          method: any
      - http:
          path: /songs/{proxy+}
          method: any
      - http:
          path: /artists
          method: any
      - http:
          path: /artists/{proxy+}
          method: any
      - http:
          path: /charts
          method: any
      - http:
          path: /charts/{proxy+}
          method: any
 
  youtubeChartsDaily:
    handler: scrapers/youtubeScraper/youtubeChartsDaily
    events:
      - schedule:
          rate: "rate(1 day)"
          enabled: true

  youtubeChartsWeekly:
    handler: scrapers/youtubeScraper/youtubeChartsWeekly
    events:
      - schedule:
          rate: "rate(7 days)"
          enabled: true

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-offline-scheduler


resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    accessKeyId: x
    secretAccessKey: x
    queues:
      - QueueName: data-raw-q
  serverless-offline:
    port: 8001    
  pythonRequirements:
    dockerizePip: true
