service: processor

provider:
  name: aws
  runtime: python3.11
  region: us-east-1  

functions:
  spotifyScraper:
    handler: scrapers/spotifyScraper.spotify_handler
    events:
      - httpApi: '*' # change this to crewler

  # process:
    # handler: handler.process
    # events:
    #   - sqs:
    #       arn:
    #         Fn::GetAtt:
    #           - DataRawQueue
    #           - Arn

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-music-q

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    accessKeyId: x
    secretAccessKey: x
    queues:
      - QueueName: data-music-q


