service: skibidi-pipeline

provider:
  name: aws
  runtime: python3.9
  region: us-east-1  

functions:
  process:
    handler: crud-api/app.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /genres
          method: any
      - http:
          path: /genres/{proxy+}
          method: any
      - http:
          path: /songs
          method: any
      - http:
          path: /songs/{proxy+}
          method: any
      - http:
          path: /artists
          method: any
      - http:
          path: /artists/{proxy+}
          method: any
      - http:
          path: /charts
          method: any
      - http:
          path: /charts/{proxy+}
          method: any

  tiktokBillboardScraper:
    handler: scrapers/tiktokBillboardScraper.tiktokScraper
    events:
      - schedule:
          rate: rate(7 days)
          enabled: true
      
  # spotifyScraper:
  #   handler: scrapers/spotifyScraper.spotify_handler
  #   events:
  #     - httpApi: '*' # change this to crewler

  # process:
    # handler: handler.process
    # events:
    #   - sqs:
    #       arn:
    #         Fn::GetAtt:
    #           - DataRawQueue
    #           - Arn

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-music-q

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    accessKeyId: x
    secretAccessKey: x
    queues:
      - QueueName: data-music-q
  serverless-offline:
    port: 8001    


