service: processor

provider:
  name: aws
  runtime: python3.11
  region: us-east-1  

functions:
  process:
    handler: handler.process
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - DataRawQueue
              - Arn
          batchSize: 1
          maximumRetryAttempts: 2
    timeout: 900

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    accessKeyId: x
    secretAccessKey: x
    queues:
      - QueueName: data-raw-q
