service: tiktok-billboard-scraper

provider:
  name: aws
  runtime: python3.9
  region: us-east-1  
  endpoint: http://sqs:9324

functions:
  tiktokBillboardScraper:
    handler: tiktokScraper.tiktok_handler
    timeout: 300
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true

plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline