service: scrapers

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

functions:
  youtubeChartsDaily:
    handler: youtubeScraper/youtubeChartsDaily.handler
    events:
      - schedule: rate(1 day)

  youtubeChartsWeekly:
    handler: youtubeScraper/youtubeChartsWeekly.handler
    events:
      - schedule: rate(7 days)
  
  tiktokScraper:
    handler: tiktokBillboardScraper/tiktokScraper.handler
    events:
      - schedule: rate(7 day)


plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-offline-scheduler

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324 
    region: us-east-1
    accessKeyId: accessKey
    secretAccessKey: secretKey
    queues:
      - QueueName: data-raw-q
