service: scrapers

provider:
  name: aws
  runtime: python3.11
  region: us-east-1

functions:
  youtubeChartsDaily:
    handler: youtubeScraper/youtubeChartsDaily.handler
    events:
      - schedule: rate(2 minutes)
      #- schedule: rate(1 day)
    timeout: 120

  youtubeChartsWeekly:
    handler: youtubeScraper/youtubeChartsWeekly.handler
    events:
      - schedule: rate(2 minutes)
      # - schedule: rate(7 days)
    timeout: 120

  
  tiktokScraper:
    handler: tiktokBillboardScraper/tiktokScraper.handler
    events:
      - schedule: rate(2 minutes)
      # - schedule: rate(7 days)
    timeout: 120


  spotifyScraperDaily:
    handler: spofityScraper/spotifyChartsDaily.handler
    events:
      - schedule: rate(2 minutes)
      # - schedule: rate(1 day)
    timeout: 120


  spotifyScraperWeekly:
    handler: spofityScraper/spotifyChartsWeekly.handler
    events:
      - schedule: rate(2 minutes)
      # - schedule: rate(7 days)
    timeout: 120


plugins:
  - serverless-python-requirements
  - serverless-offline-sqs
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-offline-scheduler

resources:
  Resources:
    DataRawQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: data-raw-q

custom:
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    accessKeyId: x
    secretAccessKey: x
    queues:
      - QueueName: data-raw-q
    pythonRequirements:
      dockerizePip: true

